<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MasLazu.AspNet.Framework.Domain\MasLazu.AspNet.Framework.Domain.csproj" />
    <ProjectReference Include="..\MasLazu.AspNet.Framework.Application\MasLazu.AspNet.Framework.Application.csproj" />
  </ItemGroup>

</Project>
